# Generated by Django 3.0.6 on 2020-09-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('auther', models.CharField(max_length=30)),
                ('post', models.TextField(max_length=500)),
                ('created_with', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone', models.EmailField(max_length=254)),
                ('email', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('tutor', models.CharField(max_length=30)),
                ('course_outline', models.TextField(max_length=500)),
                ('time_duration', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('next_of_kin', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=30)),
                ('created_with', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
