# Generated by Django 3.0.6 on 2020-09-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_auto_20200928_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_with',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='registration',
            name='course',
            field=models.CharField(choices=[('accounting', 'accounting'), ('hotel', 'hotel'), ('human', 'human')], default='hotel', max_length=30),
        ),
    ]
